name: Deploy site to nginx instance on karlos.olifurz.com

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build 11ty site
        run: npm run build
      
      - name: Deploy to server
        run: rsync -av --delete ./_site/ /var/www/html/

